### ISSUE TITLE
Develop a more formalised Go/No Go process that documents new opportunities

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Finance-project-issues#10]
From the report:  "

All   new funding bids are discussed by Trustees and a decision taken whether to   proceed or not. However, once the decision has bee given to proceed the bids   are not always reviewed by a second person (Trustee) before they are   submitted by the COO." 

Recommendation: 
"Develop   a more formalised Go/No Go process that documents new opportunities and the   decision-making process for proceeding with funding applications. The process   should include budget assessment as well as programmatic assessment. (section   3)"

Action taken: 
Need to write up the proper policy on this.

**Comment by joereddington-public** [comment]
A new version of the grant application policy was written and was approved by trustees at the 7th October 2019 meeting. This policy is in the [public policies](https://www.dropbox.com/home/eQuality%20Time/Public/Policies) folder.
