### ISSUE TITLE
The reserves policy should state a minimum reserve target. An expenditure budget for the next financial year is required to test whether eQuality Time are operating within their reserves policy of 50% of annual expenditure.

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Finance-project-issues#18]

**Comment by joereddington** [comment]
Per yearly budget and balance sheet - we expect to spend 36,000 this year and have funds of £33k. 

The reserves policy is current: 

> As a direct consequence of its aims and the projects that it supports, eQuality Time should hold a reasonable amount of money in its accounts to cover future expenses.  
> 
> eQuality Time commits to hold in reserve enough money to cover any committed outgoings including the minimum salary costs associated with any employees and all liabilities.  
> 
> At its meeting in March 2018 The Board of trustees has set a target of 50% of annual expenditure as reasonable level of reserves.  The level of reserves that is required to be held, and the reserves policy will be reviewed yearly at, or in advance of, the AGM.

 

and I would like to change that to:

> As a direct consequence of its aims and the projects that it supports, eQuality Time should hold a reasonable amount of money in its accounts to cover future expenses.  
> 
> eQuality Time commits to hold in reserve the larger of:  
>* enough money to cover any committed outgoings including the minimum salary costs associated with any employees for six months and all liabilities, 
>* £10,000 
> 
> At its meeting in March 2018 The Board of trustees has set a target of 50% of annual expenditure as reasonable level of reserves.  The level of reserves that is required to be held, and the reserves policy will be reviewed yearly at, or in advance of, the AGM.

**Comment by joereddington-public** [comment]
I think this is done...  New Policy was approved 7th October 2019, but hasn't been updated in the files. Will add.

**Comment by joereddington** [comment]
Apparently I hadn't done this. Have now.
